inherit_gem:
  syntax_tree: config/rubocop.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Style/Documentation:
  Enabled: false

Lint/ScriptPermission:
  Enabled: false

Metrics:
  Enabled: false

Style/GuardClause:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

