version: '2.4'
services:
  main:
    build: .
    ports:
      - "${RUBY_PORT:?}:4567"
    environment:
      - DOCKER=true
      - PORT=4567
      - PUBLIC=$PUBLIC
    cpus: 0.05
  bg_server:
    build: bg_server
    environment:
      - PORT=8000
    cpus: 0.95