version: '3'
services:
  main:
    build: .
    ports:
      - "${RUBY_PORT:?}:4567"
    environment:
      - DOCKER=true
      - PORT=4567
      - PUBLIC=$PUBLIC
    deploy:
      resources:
        limits:
          cpus: "0.005"
  bg_server:
    build: bg_server
    environment:
      - PORT=8000
    deploy:
      resources:
        limits:
          cpus: "0.045"